"""updated arb opportunity

Revision ID: 8d5f5325d5b9
Revises: d0acd6457921
Create Date: 2024-08-18 01:23:05.590589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d5f5325d5b9'
down_revision = 'd0acd6457921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arb_opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('commence_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('league', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('game_title', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arb_opportunity', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('game_title')
        batch_op.drop_column('league')
        batch_op.drop_column('commence_time')

    # ### end Alembic commands ###
