"""updated arb opportunity

Revision ID: b09c313a62ce
Revises: 8d5f5325d5b9
Create Date: 2024-08-21 23:15:13.116943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b09c313a62ce'
down_revision = '8d5f5325d5b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arb_opportunity', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_sent', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('arb_opportunity', schema=None) as batch_op:
        batch_op.drop_column('time_sent')

    # ### end Alembic commands ###
