"""create arb opportunity table

Revision ID: d0acd6457921
Revises: 62381086322e
Create Date: 2024-08-17 15:40:02.167545

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0acd6457921'
down_revision = '62381086322e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arb_opportunity',
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('line_1', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('line_2', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_value', sa.Float(), nullable=False),
    sa.Column('last_update', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('arb_opportunity')
    # ### end Alembic commands ###
