"""modify Game property

Revision ID: 62381086322e
Revises: 398da8d47ee7
Create Date: 2024-08-14 20:44:37.743212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62381086322e'
down_revision = '398da8d47ee7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_id', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('odd_id', sa.String(), nullable=False))
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('odd_id')
        batch_op.drop_column('game_id')

    # ### end Alembic commands ###
